In [ ]:
! python3 main.py --train "/home/vika/targer/data/NER/Indian_dataset/train.csv" --dev "/home/vika/targer/data/NER/Indian_dataset/dev.csv" --data-io connl-ner-2003 --evaluator f1-alpha-match-10 --model 'BiRNN' --opt adam --lr 0.001 --save-best yes --patience 20 --rnn-hidden-dim 200 --gpu 0 --test "/home/vika/targer/data/NER/Indian_dataset/test.csv" --elmo False --lr 0.001 --evaluator f1-macro --bert True 

args train = /home/vika/targer/data/NER/Indian_dataset/train.csv
Loading from /home/vika/targer/data/NER/Indian_dataset/train.csv: 23999 samples, 448609 words.
Loading from /home/vika/targer/data/NER/Indian_dataset/dev.csv: 1803 samples, 33827 words.
Loading from /home/vika/targer/data/NER/Indian_dataset/test.csv: 1093 samples, 18921 words.
word_sequences_train ['i', 'upgraded', 'from', 'a', 'smaller', 'sony', 'sub', 'that', 'was', 'part', 'of', 'a', '5', '1', 'speaker', 'set', 'that', 'came', 'with', 'my', 'receiver']
tag_sequences_train ['PROD1', 'PRED', 'NONE', 'NONE', 'NONE', 'PROD2', 'NONE', 'NONE', 'NONE', 'NONE', 'NONE', 'NONE', 'NONE', 'NONE', 'NONE', 'NONE', 'NONE', 'NONE', 'NONE', 'NONE', 'NONE']
DatasetsBank: len(unique_words_list) = 16615 unique words.
DatasetsBank: len(unique_words_list) = 17208 unique words.
DatasetsBank: len(unique_words_list) = 17829 unique words.
qu False
4
create seq indexer BERT!
loading vocabulary file /home/vika/targer/pretrained/uncased_L-12_H-768

In [ ]:
B-OBJ = f1 = 72.90, precision = 77.29, recall = 68.98
B-PREDFULL = f1 = 61.46, precision = 54.22, recall = 70.93
I-OBJ = f1 = 0.00, precision = 0.00, recall = 0.00
I-PREDFULL = f1 = 67.58, precision = 64.35, recall = 71.15
O = f1 = 96.41, precision = 95.67, recall = 97.16

In [1]:
!nvidia-smi

Tue Oct 15 01:03:23 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.87                 Driver Version: 390.87                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:05:00.0 Off |                  N/A |
| 35%   54C    P8    19W / 250W |    773MiB / 11170MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:06:00.0 Off |                  N/A |
| 51%   73C    P2    85W / 250W |   4198MiB / 11178MiB |     28%      Default |
+-------------------------------+----------------------+----------------------+
|   2  G

In [3]:
import torch

a = torch.load('answer.pth')
b = torch.load('index.pth')
c = torch.load('self_tensor1.pth')
d = torch.load('token_tensor.pth')
f = torch.load('encoded_layers.pth')

In [4]:
a[0][0,:,:5]

tensor([[ 1.3613, -3.6562,  1.3574,  5.7123, -6.4745],
        [ 1.3811, -3.5984,  1.4607,  6.8327, -7.5562],
        [ 1.3470, -3.8593,  1.7187,  7.2637, -7.1724],
        [ 1.2666, -3.1740,  1.2468,  6.8762, -7.5805],
        [ 1.3244, -3.1887,  1.4618,  7.2793, -4.2320],
        [ 1.4404, -3.5569,  1.4535,  7.7213, -7.4975],
        [ 1.0332, -3.8156,  1.4881,  7.7240, -6.5270],
        [ 1.3814, -2.9273,  1.4611,  7.4868, -6.3432],
        [ 1.3607, -3.7643,  1.7103,  6.9592, -7.6278],
        [ 0.6985, -3.8065,  1.3775,  5.7472, -7.6190],
        [ 0.6302, -3.0828,  0.6989,  7.7069, -7.6807],
        [ 0.7597, -3.7258,  0.9455,  7.6786, -7.1789],
        [ 1.2883, -3.6161,  0.7259,  5.3001, -5.9318],
        [ 0.6147, -3.6421,  1.4251,  6.2506, -7.3509],
        [ 1.2497, -2.6943,  1.6016,  7.1442, -7.6118],
        [ 1.1236, -3.7036,  1.5411,  7.0981, -7.6096],
        [ 1.2301, -3.7275,  1.6789,  7.7935, -7.1704],
        [ 1.2993, -3.2318,  1.4254,  6.7568, -7.2071],
        [ 

In [3]:
batch_embeddings = []
for batch_i in range(d[0].shape[0]): #batch_size
    token_embeddings = []
    for token_i in range(d[0].shape[1]):  #number of token in batch element
        hidden_layers = [] 
        for layer_i in range(len(f[0])):
            vec = f[0][layer_i][batch_i][token_i]
            hidden_layers.append(vec)
        token_embeddings.append(hidden_layers)
    summed_last_4_layers = [torch.sum(torch.stack(layer)[-4:], 0) for layer in token_embeddings]
    summed_last_4_layers = torch.stack(summed_last_4_layers)
    batch_embeddings.append(summed_last_4_layers)

answer = torch.stack(batch_embeddings) 

In [4]:
answer[0,:,:5]

tensor([[ 0.9893,  0.2826,  1.2681,  1.2064, -0.6610],
        [ 0.4920,  0.4209,  1.1853,  1.1908, -0.6767],
        [ 0.8199,  0.4248,  1.1671,  1.3297, -0.9326],
        [ 0.6627,  0.5955,  1.4539,  1.2195, -0.5065],
        [ 0.8780,  0.4360,  1.0800,  1.1473, -0.6266],
        [ 0.8378,  0.4508,  1.2516,  1.3484, -0.8536],
        [ 0.8358,  0.4692,  1.1450,  1.1634, -0.7156],
        [ 0.7691,  0.1528,  0.9802,  1.1706, -0.6026],
        [ 0.8942,  0.4878,  1.1039,  1.0773, -0.4014],
        [ 0.8619,  0.2270,  0.7334,  1.0017, -0.6570],
        [ 0.8472,  0.6062,  1.1520,  1.1398, -0.7520],
        [ 0.8631,  0.4388,  1.1885,  1.1244, -0.4540],
        [ 0.8302,  0.2417,  1.0440,  1.1638, -0.5801],
        [ 0.8355,  0.3575,  0.5310,  1.1016, -0.6472],
        [ 0.8825,  0.4304,  1.0542,  1.4129, -0.5985],
        [ 0.8327,  0.4202,  0.7623,  1.2089, -0.6835],
        [ 0.5010,  0.3375,  1.1762,  1.3705, -0.7708],
        [ 0.5229,  0.2402,  0.5606,  1.3117, -0.6126],
        [ 

In [18]:
f[0][10][0,:, 5]

tensor([-0.0648, -0.1361, -0.0713, -0.0623, -0.1207, -0.1038, -0.1765, -0.0665,
        -0.0741, -0.1469,  0.0411, -0.0504, -0.1846, -0.0663, -0.1573, -0.1244,
        -0.1101, -0.1713, -0.0625, -0.1255, -0.1611, -0.1153, -0.1704, -0.1119,
        -0.0439, -0.0675, -0.1214, -0.1203, -0.1019, -0.1244, -0.1384, -0.0495,
        -0.0975, -0.1016, -0.0716, -0.0783, -0.0182, -0.1012, -0.0937, -0.1249,
        -0.0844, -0.0722, -0.1134, -0.1770, -0.1207, -0.1154, -0.0988, -0.1692,
         0.0002, -0.1079, -0.0402, -0.1104, -0.0891, -0.0841, -0.0974],
       device='cuda:0', grad_fn=<SelectBackward>)

In [13]:
a[0][0, :, :5]

tensor([[ 0.2310, -1.4246, -0.5752,  0.7972, -2.9637],
        [ 0.1142, -1.9174, -0.7985,  0.4218, -3.1890],
        [-0.0349, -1.4001, -0.8697,  1.3980, -4.1933],
        [ 1.0246, -1.9242, -0.6518,  0.9145, -3.3030],
        [-0.2269, -1.2031, -0.6052,  0.9763, -4.3236],
        [ 0.7270, -1.7006, -0.6023,  0.7419, -3.6929],
        [ 0.7520, -1.1643, -0.6135,  0.6496, -4.2519],
        [ 0.2550, -1.6039, -0.3588,  1.0800, -4.3409],
        [ 0.6947, -1.3939, -0.8647,  0.3908, -2.8573],
        [ 0.7784, -1.6870, -0.5853,  1.0189, -2.8029],
        [ 0.2553, -1.2303, -0.9118,  0.7660, -3.6057],
        [-0.0664, -0.1857, -1.0239,  1.0297, -4.3019],
        [ 0.0318, -1.7155, -0.5830,  1.0159, -3.3180],
        [ 1.2713, -1.5704, -0.8206,  0.5319, -3.4467],
        [ 0.4250, -1.2194, -0.4668,  0.8713, -4.2420],
        [ 0.7625, -1.6525, -0.2535,  0.7632, -4.2304],
        [ 0.1344, -0.8862, -0.5777,  0.9692, -3.8707],
        [ 0.6070, -1.4817, -0.6725,  0.7431, -4.0146],
        [ 

In [2]:
d[0].shape

torch.Size([20, 60])

In [ ]:
! python3 main.py --train "/home/vika/targer/data/NER/Indian_dataset/train.csv" --dev "/home/vika/targer/data/NER/Indian_dataset/dev.csv" --data-io connl-ner-2003 --evaluator f1-alpha-match-10 --model 'BiRNN' --opt adam --lr 0.001 --save-best yes --patience 20 --rnn-hidden-dim 200 --gpu 3 --test "/home/vika/targer/data/NER/Indian_dataset/test.csv" --elmo True --evaluator f1-macro 

Using TensorFlow backend.
args train = /home/vika/targer/data/NER/Indian_dataset/train.csv
Loading from /home/vika/targer/data/NER/Indian_dataset/train.csv: 23999 samples, 448609 words.
Loading from /home/vika/targer/data/NER/Indian_dataset/dev.csv: 1803 samples, 33827 words.
Loading from /home/vika/targer/data/NER/Indian_dataset/test.csv: 1093 samples, 18921 words.
DatasetsBank: len(unique_words_list) = 16615 unique words.
DatasetsBank: len(unique_words_list) = 17208 unique words.
DatasetsBank: len(unique_words_list) = 17829 unique words.
qu True
True
False
2
create seq indexer elmo!

load_vocabulary_from_tag_sequences:
 -- class_num = 5
 -- {'<pad>': 0, 'NONE': 1, 'PROD1': 2, 'PRED': 3, 'ASP': 4, 'PROD2': 5}
LayerContextWordEmbeddings init

Start training...



++ predicting, batch 2399/2399 (100.00%).
F1 scores
------------------------
            ASP = 2.12
           NONE = 1.40
           PRED = 12.96
          PROD1 = 4.80
          PROD2 = 7.91
------------------------
Macro-F1

In [1]:
from allennlp.modules.elmo import Elmo, batch_to_ids


In [1]:
sentences = [['1tb', 'of', 'mechanical', 'storage', 'is', "n't", 'bad', '"', 'but', 'toshiba', 'hard', 'drives', 'really', 'are', "n't", 'what', 'we', 'want', 'to', 'be', 'seeing', 'as', 'they', 'tend', 'to', 'be', 'a', 'bit', 'slower', 'than', 'competing', 'drives', 'from', 'hgst', '"', 'western', 'digital', '"', 'samsung', '"', 'and', 'seagate', '.'],  ['we', 'have', 'found', 'that', 'blood', 'carbon', 'and', 'nitrogen', 'turnover', 'was', 'roughly', 'equivalent', 'in', 'mice', 'and', 'in', 'rats', '"', 'and', 'that', 'mouse', 'blood', 'turned', 'over', 'slightly', 'faster', 'than', 'rat', 'blood', '.']]

In [8]:
for elem in zip(sentences[0], tags[0]):
    print (elem)

('1tb', 'O')
('of', 'O')
('mechanical', 'O')
('storage', 'O')
('is', 'O')
("n't", 'O')
('bad', 'O')
('"', 'O')
('but', 'O')
('toshiba', 'B-OTHOBJ')
('hard', 'O')
('drives', 'O')
('really', 'O')
('are', 'O')
("n't", 'O')
('what', 'O')
('we', 'O')
('want', 'O')
('to', 'O')
('be', 'O')
('seeing', 'O')
('as', 'O')
('they', 'O')
('tend', 'O')
('to', 'O')
('be', 'O')
('a', 'O')
('bit', 'O')
('slower', 'O')
('than', 'O')
('competing', 'O')
('drives', 'O')
('from', 'O')
('hgst', 'O')
('"', 'O')
('western', 'O')
('digital', 'O')
('"', 'O')
('samsung', 'B-ASPOBJ')
('"', 'O')
('and', 'O')
('seagate', 'O')
('.', 'O')


In [3]:
from src.factories.factory_tagger import TaggerFactory
import torch

model = TaggerFactory.load("2019_09_24_10-48_48_tagger.hdf5")
model.gpu = 1
model.cuda(device = 1)


tags = model.predict_tags_from_words(sentences)



++ predicting, batch 1/1 (0.00%).

In [2]:
! pip3 install pip install --trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org pytorch-pretrained-bert

  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f23f7295240>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/install/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f23f72951d0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/install/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f23f72950f0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/install/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip

In [1]:
import torch
from pytorch_pretrained_bert import BertTokenizer, BertModel, BertForMaskedLM


In [2]:
input_ids = torch.tensor([tokenizer.encode("Let's see all hidden-states and attentions on this text")])

NameError: name 'tokenizer' is not defined

In [3]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
words = string.join(words)

NameError: name 'string' is not defined

In [16]:
sentences = ['we have found that blood carbon and nitrogen turnover was roughly equivalent', 'in mice and in rats "and that mouse blood turned over .']

In [24]:
text = ["Here", "is", "the", "sentence", "I", "want", "embeddings", "for", "."]
#text = "After stealing money from the bank vault, the bank robber was seen fishing on the Mississippi river bank."
marked_text = text

In [29]:
tokenized_texts = tokenizer.tokenize("".join(text))
print(tokenized_texts)
i = 0
word_index = []
next_word = False
for token in tokenized_texts:
    if (next_word):
        i += 1
    word_index.append(i)
    if ('##' in token):
        next_word = False
    else:
        next_word = True
print (word_index)   

['here', 'is', 'the', 'sentence', 'i', 'want', 'em', '##bed', '##ding', '##s', 'for', '.']
[0, 1, 2, 3, 4, 5, 6, 7, 7, 7, 7, 8]


In [16]:
from keras.preprocessing.sequence import pad_sequences
import numpy as np
MAX_LEN = np.max(np.array([len(seq) for seq in tokenized_texts]))
input_ids = pad_sequences([tokenizer.convert_tokens_to_ids(txt) for txt in tokenized_texts], maxlen=MAX_LEN, dtype="long", truncating="post", padding="post")

In [19]:
input_ids

numpy.ndarray

In [17]:
MAX_LEN

22

In [4]:
words = ''.join(words)

TypeError: sequence item 0: expected str instance, list found

In [39]:
len(indexed_tokens2)

16

In [24]:
tokens_tensor = torch.tensor(input_ids)
segments_tensors = torch.tensor(np.ones(input_ids.shape)).to(torch.int64)

# Load pre-trained model (weights)
model = BertModel.from_pretrained("pretrained")#BertModel.from_pretrained('bert-base-uncased')

# Put the model in "evaluation" mode, meaning feed-forward operation.
#model.eval()

In [25]:
type(tokens_tensor)

torch.Tensor

In [26]:
type(segments_tensors)

torch.Tensor

In [27]:
with torch.no_grad():
    encoded_layers, _ = model(tokens_tensor, segments_tensors)

In [37]:
len(encoded_layers[2][1][21])

768

In [35]:
len(tokenizer.vocab.keys())

30522

In [29]:
token_embeddings = [] 

# For each token in the sentence...
for token_i in range(len(tokenized_text)):  
    # Holds 12 layers of hidden states for each token 
    hidden_layers = [] 
    # For each of the 12 layers...
    for layer_i in range(len(encoded_layers)):
    # Lookup the vector for `token_i` in `layer_i`
        vec = encoded_layers[layer_i][0][token_i]
        hidden_layers.append(vec)
        token_embeddings.append(hidden_layers)

summed_last_4_layers = [torch.sum(torch.stack(layer)[-4:], 0) for layer in token_embeddings]

In [30]:
len(summed_last_4_layers)

540

In [ ]:
text = "Here is the sentence I want embeddings for."
text = "After stealing money from the bank vault, the bank robber was seen fishing on the Mississippi river bank."
marked_text = "[CLS] " + text + " [SEP]"

print (marked_text)

In [33]:
from allennlp.modules.elmo import Elmo, batch_to_ids

options_file = "embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_options.json"
weight_file = "/home/vika/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_weights.hdf5"

# Compute two different representation for each token.
# Each representation is a linear weighted combination for the
# 3 layers in ELMo (i.e., charcnn, the outputs of the two BiLSTM))
elmo = Elmo(options_file, weight_file, 2, dropout=0)

# use batch_to_ids to convert sentences to character ids
sentences = [['1tb', 'of', 'mechanical', 'storage', 'is', "n't", 'bad', '"', 'but', 'toshiba', 'hard', 'drives', 'really', 'are', "n't", 'what', 'we', 'want', 'to', 'be', 'seeing', 'as', 'they', 'tend', 'to', 'be', 'a', 'bit', 'slower', 'than', 'competing', 'drives', 'from', 'hgst', '"', 'western', 'digital', '"', 'samsung', '"', 'and', 'seagate', '.'], ['amazon', 'is', 'another', 'good', 'choice', '"', 'and', 'i', 'actually', 'prefer', 'their', 'interface', 'better', 'than', 'itunes', '', '(', 'it', 'loads', 'faster', 'for', 'me', ')', '.'], ['well-designed', '"', 'properly', 'constructed', 'timber', 'buildings', 'can', 'be', 'even', 'safer', 'in', 'earthquakes', 'than', 'ferro-concrete', 'ones', '.'], ['maybe', 'it', 's', 'because', 'i', 'm', 'a', 'ku', 'fan', '"', 'but', 'i', 'honestly', 'like', 'the', 'looks', 'of', 'adidas', 'uniforms', 'better', 'than', 'nike', '.'], ['soft', 'drinks', 'do', 'not', 'include', 'beverages', 'that', 'contain', 'milk', 'or', 'milk', 'products', '"', 'soy', '"', 'rice', 'or', 'similar', 'milk', 'substitutes', '"', 'or', 'greater', 'than', '50', '%', 'of', 'vegetable', 'or', 'fruit', 'juice', 'by', 'volume', '.'], ['partly', 'because', 'i', 'like', 'apple', 's', 'choice', 'of', 'file', 'format', '-', 'aac', 'is', 'much', 'more', 'modern', 'than', 'mp3', '"', 'and', 'theoretically', 'an', 'aac', 'file', 'at', '256kbps', '(', 'from', 'itunes', 'plus', ')', 'sounds', 'better', 'than', 'an', 'mp3', 'file', 'at', '256kbps', '(', 'from', 'amazon', ')', '.'], ['and', 'nokia', 'is', 'easier', 'to', 'use', '...', '...', 'it', 'easily', 'gets', 'infected', 'with', 'virus', 'and', 'the', 'net', 'speed', 'is', 'not', 'fast', '...', '..and', 'ofcourse', 'nokia', 'is', 'way', 'more', 'reliable', 'than', 'samsung', '...', '..go', 'for', 'nokia', '...', '..this', 'phone', 'suxxxxxxxxxxxxxxxxxxxxxx', '!'], ['java', 'is', 'a', 'static', 'type', 'language', 'and', 'it', 'is', 'safer', 'than', 'dynamic', 'type', 'languages', 'like', 'ruby', '.'], ['amazon', 'music', 'will', 'be', 'cheaper', '"', 'faster', 'and', 'perceived', 'to', 'be', 'more', 'honest', 'than', 'itunes', 'both', 'by', 'customers', 'and', 'musicians', '.'], 
             ['we', 'have', 'found', 'that', 'blood', 'carbon', 'and', 'nitrogen', 'turnover', 'was', 'roughly', 'equivalent', 'in', 'mice', 'and', 'in', 'rats', '"', 'and', 'that', 'mouse', 'blood', 'turned', 'over', 'slightly', 'faster', 'than', 'rat', 'blood', '.']]

character_ids = batch_to_ids(sentences)

embeddings = elmo(character_ids)


In [41]:
elmo.get_output_dim()

1024

In [16]:
character_ids.size()

torch.Size([10, 44, 50])

In [12]:
character_ids[2][2]

tensor([259, 113, 115, 112, 113, 102, 115, 109, 122, 260, 261, 261, 261, 261,
        261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
        261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
        261, 261, 261, 261, 261, 261, 261, 261])

In [38]:
print (embeddings['elmo_representations'][1][5][5])

tensor([-0.4785, -0.4598, -0.0396,  ..., -0.1577, -0.3011, -0.1590],
       grad_fn=<SelectBackward>)


In [39]:
print (embeddings['elmo_representations'][0][5][5])

tensor([-0.4785, -0.4598, -0.0396,  ..., -0.1577, -0.3011, -0.1590],
       grad_fn=<SelectBackward>)


## birnn 

In [ ]:
BiRNNCNN

In [1]:
! python3 main.py --train "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv" --dev "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test.csv" --test "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv" --data-io connl-ner-2003 --evaluator f1-alpha-match-10 --model BiRNNCRF --opt adam --lr 0.001 --save-best yes --patience 20 --rnn-hidden-dim 200 --gpu 1 --test "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test.csv" --save "BiRNNCFR.hdf5" 

args train = /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv: 2619 samples, 74616 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test.csv: 523 samples, 14728 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test.csv: 523 samples, 14728 words.
word_sequences_dev 523 [['and', 'can', 'i', 'just', 'say', 'that', 'doing', 'the', 'inferno', 'move', 'on', 'the', 'ds', 'is', '50', 'times', 'easier', 'than', 'trying', 'to', 'make', 'an', 'infinity', 'symbol', 'using', 'the', 'wii', 'remote', '.'], ['i', 'go', 'to', 'the', 'amazon', 'mp3', 'store', '(', 'better', 'than', 'itunes', '.'], ['tea', 'dinner', '(', 'sorry', '"', 'my', 'wife', 'is', 'trying', 'to', 'make', 'me', 'posherer', ')', 'and', 'picking', 'up', 'a', 'phone', 'is', 'easier', '-', 'then', 'i', 'can', 'swig', 'my', 'beer', 'and', 'relaaaaxxxx', '...', '.', '.'], ['actually', '

In [1]:
import torch
torch.cuda.is_available()

True

In [ ]:
! python3 main.py --train "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv" --dev "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv" --data-io connl-ner-2003 --evaluator f1-alpha-match-10 --opt adam --lr 0.001 --save-best yes --patience 20 --rnn-hidden-dim 200 --gpu 1 --test "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test.csv" --epoch-num 50 --isElmo True --save "regular_elmo.hdf5"

args train = /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv: 2619 samples, 74616 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv: 350 samples, 10092 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test.csv: 523 samples, 14728 words.
DatasetsBank: len(unique_words_list) = 7143 unique words.
DatasetsBank: len(unique_words_list) = 7600 unique words.
DatasetsBank: len(unique_words_list) = 8167 unique words.

load_vocabulary_from_tag_sequences:
 -- class_num = 7
 -- {'<pad>': 0, 'O': 1, 'B-OTHOBJ': 2, 'B-ASPOBJ': 3, 'B-ASP': 4, 'I-ASP': 5, 'I-ASPOBJ': 6, 'I-OTHOBJ': 7}
in main
True
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_weights.hdf5
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_options.json
init targer base
True
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_5

In [1]:
! python3 main.py --train "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv" --dev "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv" --data-io connl-ner-2003 --evaluator f1-alpha-match-10 --opt adam --lr 0.001 --save-best yes --patience 20 --rnn-hidden-dim 200 --gpu 1 --test "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_qw_new.csv" --epoch-num 50 --isElmo True --save "new_tagger1.hdf5"

args train = /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv: 2619 samples, 74616 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv: 350 samples, 10092 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_qw_new.csv: 63 samples, 322 words.
DatasetsBank: len(unique_words_list) = 7143 unique words.
DatasetsBank: len(unique_words_list) = 7600 unique words.
DatasetsBank: len(unique_words_list) = 7604 unique words.

load_vocabulary_from_tag_sequences:
 -- class_num = 7
 -- {'<pad>': 0, 'O': 1, 'B-OTHOBJ': 2, 'B-ASPOBJ': 3, 'B-ASP': 4, 'I-ASP': 5, 'I-ASPOBJ': 6, 'I-OTHOBJ': 7}
in main
True
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_weights.hdf5
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_options.json
init targer base
True
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_51

In [2]:
from allennlp.modules.elmo import Elmo, batch_to_ids

In [ ]:
import sys
sys.path.append('/home/vika/NER_RNN/targer')
from src.factories.factory_tagger import TaggerFactory

model = TaggerFactory.load(PATH_TO_PRETRAINED + MODEL_NAME)
model.cuda(device=1)
model.gpu = 1
tags = model.predict_tags_from_words(words)

In [1]:
! python3 main.py --train "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train_new.csv" --dev "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv" --data-io connl-ner-2003 --evaluator f1-alpha-match-10 --opt adam --lr 0.001 --save-best yes --patience 20 --rnn-hidden-dim 200 --gpu 1 --test "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test_new.csv" --epoch-num 50 --isElmo True --save "new_tagger1.hdf5"

args train = /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train_new.csv
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train_new.csv: 2719 samples, 75117 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv: 350 samples, 10092 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test_new.csv: 584 samples, 15032 words.
DatasetsBank: len(unique_words_list) = 7144 unique words.
DatasetsBank: len(unique_words_list) = 7601 unique words.
DatasetsBank: len(unique_words_list) = 8171 unique words.

load_vocabulary_from_tag_sequences:
 -- class_num = 8
 -- {'<pad>': 0, 'tag': 1, 'O': 2, 'B-OTHOBJ': 3, 'B-ASPOBJ': 4, 'B-ASP': 5, 'I-ASP': 6, 'I-ASPOBJ': 7, 'I-OTHOBJ': 8}
in main
True
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_weights.hdf5
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_options.json
init targer base
True
/home/vika/NER_RNN/targer/em

In [5]:
!pwd

/home/vika/NER_RNN/targer
