In [1]:
! python3 main.py --train "/home/vika/targer/data/NER/Varvara_v2/train_pred_full.tsv" --dev "/home/vika/targer/data/NER/Varvara_v2/dev_pred_full.tsv" --data-io connl-ner-2003 --evaluator f1-alpha-match-10 --model BiRNN --opt adam --save-best yes --patience 20 --rnn-hidden-dim 200 --gpu 2 --test "/home/vika/targer/data/NER/Varvara_v1/test_pred_full.tsv" --elmo False --epoch-num 50 --evaluator f1-macro --bert False

word_sequences_train ['miro', "'", 's', 'favorite', 'things', ':', 'color', ':', 'blue', 'team', 'growing', 'up', ':', 'czechoslovakian', 'national', 'team', 'player', 'growing', 'up', ':', 'mario', 'lemieux', 'arena', 'outside', 'long', 'island', ':', 'bell', 'centre', '(', 'montreal', ')', 'food', ':', 'italian', 'movie', ':', 'big', 'lebowski', 'car', ':', 'mercedes', 'benz', 'brand', 'of', 'skates', ':', 'bauer', 'brand', 'of', 'hockey', 'stick', ':', 'reebok', 'former', 'islander', ':', 'mike', 'bossy', 'board', 'game', ':', 'chess', 'sport', '(', 'other', 'than', 'hockey', '):', 'golf', 'band', ':', 'guns', 'n', "'", 'roses', 'vacation', 'spot', ':', 'italy', 'and', 'mexico', 'non', '-', 'north', 'american', 'city', '(', 'not', 'in', 'slovakia', '):', 'rome', 'stadium', 'food', ':', 'popcorn']
tag_sequences_train ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O'

In [ ]:
! python3 main.py --train "/home/vika/targer/data/NER/Varvara_v1/train_pred_full.tsv" --dev "/home/vika/targer/data/NER/Varvara_v1/dev_pred_full.tsv" --data-io connl-ner-2003 --evaluator f1-alpha-match-10 --model BiRNN --opt adam --save-best yes --patience 20 --rnn-hidden-dim 200 --gpu 2 --test "/home/vika/targer/data/NER/Varvara_v1/test_pred_full.tsv" --elmo False --lr 0.00001 --epoch-num 150 --evaluator f1-macro --bert True

word_sequences_train ['i', 'have', 'always', 'heard', 'that', 'motrin', 'is', 'better', 'than', 'advil', 'for', 'fevers', ',', 'and', 'that', 'advil', 'works', 'better', 'for', 'body', 'aches', 'and', 'pains', '.']
tag_sequences_train ['O', 'O', 'O', 'O', 'O', 'B-OBJ', 'O', 'O', 'O', 'B-OBJ', 'O', 'O', 'O', 'O', 'O', 'B-OBJ', 'O', 'B-PREDFULL', 'I-PREDFULL', 'I-PREDFULL', 'I-PREDFULL', 'I-PREDFULL', 'I-PREDFULL', 'O']
 -- {'<pad>': 0, 'O': 1, 'B-OBJ': 2, 'B-PREDFULL': 3, 'I-PREDFULL': 4, 'I-OBJ': 5}


In [4]:
! nvidia-smi

Fri Oct 25 09:13:20 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.87                 Driver Version: 390.87                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:05:00.0 Off |                  N/A |
| 46%   67C    P2    66W / 250W |   3756MiB / 11170MiB |      9%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:06:00.0 Off |                  N/A |
| 41%   61C    P2    59W / 250W |  10067MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  G

In [15]:
эмбеддинг оставила

torch.Size([39, 55])

In [ ]:
 for batch_i in range(len(self.word_sequences)): #batch_size
    token_embeddings = []
    for token_i in range(self.tokens_tensor.shape[1]):  #number of token in batch element
        hidden_layers = [] 
        for layer_i in range(len(encoded_layers)):
            vec = encoded_layers[layer_i][batch_i][token_i]
            hidden_layers.append(vec)
        token_embeddings.append(hidden_layers)
    summed_last_4_layers = [torch.sum(torch.stack(layer)[-4:], 0) for layer in token_embeddings]
    summed_last_4_layers = torch.stack(summed_last_4_layers)
    batch_embeddings.append(summed_last_4_layers)

In [14]:
g[0].size()

torch.Size([39, 55, 768])

In [11]:
import torch
c = torch.load('fnm.pth')[0]

In [16]:
a = torch.load('answer.pth')[0]
index = torch.load('index.pth')[0]
self_tensor1 = torch.load('self_tensor1.pth')[0]
token_tensor = torch.load('token_tensor.pth')[0]

In [17]:
token_tensor.shape

torch.Size([39, 55])

In [5]:
a[0][0,:,:5]

tensor([[-0.6372, -1.8235,  0.1793,  5.3915, -1.2148],
        [-0.6372, -1.8235,  0.1793,  5.3915, -1.2148],
        [-0.6372, -1.8235,  0.1793,  5.3915, -1.2148],
        [-0.6372, -1.8235,  0.1793,  5.3916, -1.2148],
        [-0.6372, -1.8235,  0.1793,  5.3915, -1.2148],
        [-0.6372, -1.8235,  0.1793,  5.3915, -1.2148],
        [-0.6372, -1.8235,  0.1793,  5.3915, -1.2148],
        [-0.6372, -1.8235,  0.1793,  5.3915, -1.2148],
        [-0.6372, -1.8235,  0.1793,  5.3915, -1.2148],
        [-0.6372, -1.8235,  0.1793,  5.3915, -1.2148],
        [-0.6372, -1.8235,  0.1793,  5.3915, -1.2148],
        [-0.6372, -1.8235,  0.1793,  5.3915, -1.2148],
        [-0.6372, -1.8235,  0.1793,  5.3915, -1.2148],
        [-0.6372, -1.8235,  0.1793,  5.3915, -1.2148],
        [-0.6372, -1.8235,  0.1793,  5.3915, -1.2148],
        [-0.6372, -1.8235,  0.1793,  5.3915, -1.2148],
        [-0.6372, -1.8235,  0.1793,  5.3915, -1.2148],
        [-0.6372, -1.8235,  0.1793,  5.3915, -1.2148],
        [-

In [8]:
b[0][0,:,:5]

tensor([[ 0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4],
        [ 5,  5,  5,  5,  5],
        [ 6,  6,  6,  6,  6],
        [ 7,  7,  7,  7,  7],
        [ 8,  8,  8,  8,  8],
        [ 9,  9,  9,  9,  9],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [11, 11, 11, 11, 11],
        [12, 12, 12, 12, 12],
        [13, 13, 13, 13, 13],
        [14, 14, 14, 14, 14],
        [15, 15, 15, 15, 15],
        [16, 16, 16, 16, 16],
        [17, 17, 17, 17, 17],
        [18, 18, 18, 18, 18],
        [19, 19, 19, 19, 19],
        [20, 20, 20, 20, 20],
        [21, 21, 21, 21, 21],
        [22, 22, 22, 22, 22],
        [23, 23, 23, 23, 23],
        [24, 24, 24, 24, 24],
        [25, 25, 25, 25, 25],
        [26, 26, 26, 26, 26],
        [27, 27, 27, 27, 27],
        [28, 28, 28, 28, 28],
        [29, 29, 29, 29, 29],
        [30, 30, 30, 30, 30],
        [3

In [2]:
!nvidia-smi

Wed Oct 23 08:24:50 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.87                 Driver Version: 390.87                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:05:00.0 Off |                  N/A |
| 36%   56C    P8    19W / 250W |   1169MiB / 11170MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:06:00.0 Off |                  N/A |
| 47%   69C    P2    62W / 250W |   5405MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  G

In [1]:
import torch
print(torch.__version__)

0.4.1


In [1]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176


In [2]:
import torch
torch.cuda.is_available()

False

In [3]:
import tensorflow

In [5]:
tensorflow.python.keras.backend.image_dim_ordering()

AttributeError: module 'tensorflow' has no attribute 'python'

In [4]:
!nvidia-smi

Sun Oct 13 23:41:19 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.87                 Driver Version: 390.87                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:05:00.0 Off |                  N/A |
| 46%   67C    P8    21W / 250W |   2301MiB / 11170MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:06:00.0 Off |                  N/A |
| 84%   90C    P2   100W / 250W |   8247MiB / 11178MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   2  G

In [23]:
import torch
import torch.nn.functional as F

seq = torch.Tensor([[1,2,3, 4], [1,2,3, 4], [1,2,3, 3]]) 
print (seq.shape)# seq of variable length
seq = F.pad(seq, pad=(0, 0, 0, 1), mode='constant', value=0)
print (seq.shape)
print (seq)

torch.Size([3, 4])
torch.Size([4, 4])
tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 3.],
        [0., 0., 0., 0.]])


In [8]:
import torch
import torch.nn.functional as F
mask_tensor = torch.load("mask_tensor.pth")

RuntimeError: unexpected EOF. The file might be corrupted.

In [67]:
self_tensor = F.pad(self_tensor, [0,0,0,1,0,0])

In [39]:
self_tensor1 = self_tensor.scatter_add(1, index[..., None], answer)
        

RuntimeError: Invalid index in scatterAdd at /pytorch/aten/src/TH/generic/THTensorMath.cpp:680

In [41]:
self_tensor[index, :] = answer

RuntimeError: index 44 is out of bounds for dimension 0 with size 10

In [5]:
import torch
t = torch.tensor([[1,2],[3,4]])
r = torch.gather(t, 0, torch.tensor([[0,0],[1,0]]))

In [6]:
r

tensor([[1, 2],
        [3, 2]])

In [12]:
import torch
x = torch.tensor([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]).float()

a = torch.ones(2, 4)


indexes = torch.tensor([[0, 1, 2, 0], [2, 0, 0, 1]])
print ("self shape ", a.shape)
print ("indexes shape ", indexes.shape)
print ("source ", x.shape)
a.scatter_add_(1, torch.tensor([[0, 1, 2, 0], [2, 0, 0, 1]]), x)

self shape  torch.Size([2, 4])
indexes shape  torch.Size([2, 4])
source  torch.Size([2, 5])


tensor([[ 4.,  2.,  3.,  1.],
        [14.,  9.,  6.,  1.]])

In [5]:
!export LC_ALL= en_US.UTF-8

/bin/sh: 1: export: en_US.UTF-8: bad variable name


In [4]:
locale.setlocale(locale.LC_ALL, str('en_US.UTF-8'))

Error: unsupported locale setting

In [2]:
locale.setlocale(locale.LC_ALL, 'es_ES.UTF8')

Error: unsupported locale setting

In [24]:
!export LC_ALL="en_US.UTF-8"
!export LC_CTYPE="en_US.UTF-8"

In [20]:
print("preço")

preço


In [12]:
!dpkg-reconfigure locales

/usr/sbin/dpkg-reconfigure must be run as root


In [15]:
LANG="en_US.UTF-8"
LANGUAGE="en_US:en"

In [19]:
!locale

LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=


In [14]:
!export LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

In [8]:
!locale -a

C
C.UTF-8
POSIX


In [2]:
!export LANG=en_US.UTF-8 LANGUAGE=en_US.en LC_ALL=en_US.UTF-8

In [8]:
 print ("loading vocabulary file %s"%a)

loading vocabulary file rr


In [1]:
from pytorch_pretrained_bert import BertTokenizer, BertModel, BertForMaskedLM
from src.tokenizers import tokenizer_custom_bert

In [2]:
a = tokenizer_custom_bert.BertTokenizer.from_pretrained('bert-base-uncased')

loading vocabulary file /home/vika/targer/pretrained/uncased_L-12_H-768_A-12/vocab.txt
resolved voc file /home/vika/targer/pretrained/uncased_L-12_H-768_A-12/vocab.txt


In [5]:
a.tokenize(text)

1 1tb of mechanical storage is n't bad , mini-wan but toshiba hard drives really are n't what we want to be seeing as they tend to be a bit slower than competing drives from hgst , western digital , samsung , and seagate .  amazon is another good choice , and i actually prefer their interface better than itunes
2 1tb of mechanical storage is n't bad , mini-wan but toshiba hard drives really are n't what we want to be seeing as they tend to be a bit slower than competing drives from hgst , western digital , samsung , and seagate .  amazon is another good choice , and i actually prefer their interface better than itunes
3 ['1tb', 'of', 'mechanical', 'storage', 'is', "n't", 'bad', ',', 'mini-wan', 'but', 'toshiba', 'hard', 'drives', 'really', 'are', "n't", 'what', 'we', 'want', 'to', 'be', 'seeing', 'as', 'they', 'tend', 'to', 'be', 'a', 'bit', 'slower', 'than', 'competing', 'drives', 'from', 'hgst', ',', 'western', 'digital', ',', 'samsung', ',', 'and', 'seagate', '.', 'amazon', 'is', 'a

['1',
 '##t',
 '##b',
 'of',
 'mechanical',
 'storage',
 'is',
 'n',
 "##'",
 '##t',
 'bad',
 ',',
 'mini',
 '##-',
 '##wan',
 'but',
 'to',
 '##shi',
 '##ba',
 'hard',
 'drives',
 'really',
 'are',
 'n',
 "##'",
 '##t',
 'what',
 'we',
 'want',
 'to',
 'be',
 'seeing',
 'as',
 'they',
 'tend',
 'to',
 'be',
 'a',
 'bit',
 'slower',
 'than',
 'competing',
 'drives',
 'from',
 'h',
 '##gs',
 '##t',
 ',',
 'western',
 'digital',
 ',',
 'samsung',
 ',',
 'and',
 'sea',
 '##gate',
 '.',
 'amazon',
 'is',
 'another',
 'good',
 'choice',
 ',',
 'and',
 'i',
 'actually',
 'prefer',
 'their',
 'interface',
 'better',
 'than',
 'itunes']

In [4]:
text = "1tb of mechanical storage is n't bad , mini-wan but toshiba hard drives really are n't what we want to be seeing as they tend to be a bit slower than competing drives from hgst , western digital , samsung , and seagate .  amazon is another good choice , and i actually prefer their interface better than itunes"

In [22]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

In [56]:
tokenizer_b = BasicTokenizer()

In [1]:
! python3 main.py --train "/home/vika/targer/data/NER/Varvara/train.csv" --dev "/home/vika/targer/data/NER/Varvara/dev.csv" --data-io connl-ner-2003 --evaluator f1-macro --model 'BiRNN' --opt adam --lr 0.001 --save-best yes --patience 20 --rnn-hidden-dim 200 --gpu 2 --test "/home/vika/targer/data/NER/Varvara/test.csv" --elmo True 

Using TensorFlow backend.
args train = /home/vika/targer/data/NER/Varvara/train.csv
Loading from /home/vika/targer/data/NER/Varvara/train.csv: 2433 samples, 68029 words.
Loading from /home/vika/targer/data/NER/Varvara/dev.csv: 358 samples, 9091 words.
Loading from /home/vika/targer/data/NER/Varvara/test.csv: 369 samples, 10163 words.
DatasetsBank: len(unique_words_list) = 7276 unique words.
DatasetsBank: len(unique_words_list) = 8004 unique words.
DatasetsBank: len(unique_words_list) = 8570 unique words.
qu True
True
False
2
create seq indexer elmo!

load_vocabulary_from_tag_sequences:
 -- class_num = 5
 -- {'<pad>': 0, 'O': 1, 'B-OBJ': 2, 'B-PREDFULL': 3, 'I-PREDFULL': 4, 'I-OBJ': 5}
LayerContextWordEmbeddings init

Start training...



++ predicting, batch 243/243 (100.00%).
F1 scores
------------------------
          B-OBJ = f1 = 4.93, precision = 4.06, recall = 6.27
     B-PREDFULL = f1 = 2.70, precision = 1.38, recall = 60.95
          I-OBJ = f1 = 0.00, precision = 0.00, recall 

In [1]:
from allennlp.modules.elmo import Elmo, batch_to_ids


In [1]:
sentences = [['1tb', 'of', 'mechanical', 'storage', 'is', "n't", 'bad', '"', 'but', 'toshiba', 'hard', 'drives', 'really', 'are', "n't", 'what', 'we', 'want', 'to', 'be', 'seeing', 'as', 'they', 'tend', 'to', 'be', 'a', 'bit', 'slower', 'than', 'competing', 'drives', 'from', 'hgst', '"', 'western', 'digital', '"', 'samsung', '"', 'and', 'seagate', '.'],  ['we', 'have', 'found', 'that', 'blood', 'carbon', 'and', 'nitrogen', 'turnover', 'was', 'roughly', 'equivalent', 'in', 'mice', 'and', 'in', 'rats', '"', 'and', 'that', 'mouse', 'blood', 'turned', 'over', 'slightly', 'faster', 'than', 'rat', 'blood', '.']]

In [8]:
for elem in zip(sentences[0], tags[0]):
    print (elem)

('1tb', 'O')
('of', 'O')
('mechanical', 'O')
('storage', 'O')
('is', 'O')
("n't", 'O')
('bad', 'O')
('"', 'O')
('but', 'O')
('toshiba', 'B-OTHOBJ')
('hard', 'O')
('drives', 'O')
('really', 'O')
('are', 'O')
("n't", 'O')
('what', 'O')
('we', 'O')
('want', 'O')
('to', 'O')
('be', 'O')
('seeing', 'O')
('as', 'O')
('they', 'O')
('tend', 'O')
('to', 'O')
('be', 'O')
('a', 'O')
('bit', 'O')
('slower', 'O')
('than', 'O')
('competing', 'O')
('drives', 'O')
('from', 'O')
('hgst', 'O')
('"', 'O')
('western', 'O')
('digital', 'O')
('"', 'O')
('samsung', 'B-ASPOBJ')
('"', 'O')
('and', 'O')
('seagate', 'O')
('.', 'O')


In [3]:
from src.factories.factory_tagger import TaggerFactory
import torch

model = TaggerFactory.load("2019_09_24_10-48_48_tagger.hdf5")
model.gpu = 1
model.cuda(device = 1)


tags = model.predict_tags_from_words(sentences)



++ predicting, batch 1/1 (0.00%).

In [2]:
! pip3 install pip install --trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org pytorch-pretrained-bert

  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f23f7295240>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/install/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f23f72951d0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/install/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f23f72950f0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/install/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip

In [8]:
import torch
from pytorch_pretrained_bert import BertTokenizer, BertModel, BertForMaskedLM


In [10]:
input_ids = torch.tensor([tokenizer.encode("Let's see all hidden-states and attentions on this text")])

AttributeError: 'BertTokenizer' object has no attribute 'encode'

In [9]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
words = string.join(words)

NameError: name 'string' is not defined

In [11]:
sentences = [['we', 'have', 'found', 'that', 'blood', 'carbon', 'and', 'nitrogen', 'turnover', 'was', 'roughly', 'equivalent'], ['in', 'mice', 'and', 'in', 'rats', '"', 'and', 'that', 'mouse', 'blood', 'turned', 'over','.']]

In [13]:
tokenized_texts = [tokenizer.tokenize(''.join(sent)) for sent in sentences]
print(tokenized_texts[0])

['we', '##ha', '##ve', '##fo', '##und', '##tha', '##t', '##blood', '##carbon', '##and', '##ni', '##tro', '##gent', '##urn', '##over', '##was', '##rou', '##gh', '##ly', '##e', '##qui', '##valent']


In [16]:
from keras.preprocessing.sequence import pad_sequences
import numpy as np
MAX_LEN = np.max(np.array([len(seq) for seq in tokenized_texts]))
input_ids = pad_sequences([tokenizer.convert_tokens_to_ids(txt) for txt in tokenized_texts], maxlen=MAX_LEN, dtype="long", truncating="post", padding="post")

In [19]:
input_ids

numpy.ndarray

In [17]:
MAX_LEN

22

In [4]:
words = ''.join(words)

TypeError: sequence item 0: expected str instance, list found

In [39]:
len(indexed_tokens2)

16

In [24]:
tokens_tensor = torch.tensor(input_ids)
segments_tensors = torch.tensor(np.ones(input_ids.shape)).to(torch.int64)

# Load pre-trained model (weights)
model = BertModel.from_pretrained("pretrained")#BertModel.from_pretrained('bert-base-uncased')

# Put the model in "evaluation" mode, meaning feed-forward operation.
#model.eval()

In [25]:
type(tokens_tensor)

torch.Tensor

In [26]:
type(segments_tensors)

torch.Tensor

In [27]:
with torch.no_grad():
    encoded_layers, _ = model(tokens_tensor, segments_tensors)

In [37]:
len(encoded_layers[2][1][21])

768

In [35]:
len(tokenizer.vocab.keys())

30522

In [29]:
token_embeddings = [] 

# For each token in the sentence...
for token_i in range(len(tokenized_text)):  
    # Holds 12 layers of hidden states for each token 
    hidden_layers = [] 
    # For each of the 12 layers...
    for layer_i in range(len(encoded_layers)):
    # Lookup the vector for `token_i` in `layer_i`
        vec = encoded_layers[layer_i][0][token_i]
        hidden_layers.append(vec)
        token_embeddings.append(hidden_layers)

summed_last_4_layers = [torch.sum(torch.stack(layer)[-4:], 0) for layer in token_embeddings]

In [30]:
len(summed_last_4_layers)

540

In [ ]:
text = "Here is the sentence I want embeddings for."
text = "After stealing money from the bank vault, the bank robber was seen fishing on the Mississippi river bank."
marked_text = "[CLS] " + text + " [SEP]"

print (marked_text)

In [33]:
from allennlp.modules.elmo import Elmo, batch_to_ids

options_file = "embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_options.json"
weight_file = "/home/vika/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_weights.hdf5"

# Compute two different representation for each token.
# Each representation is a linear weighted combination for the
# 3 layers in ELMo (i.e., charcnn, the outputs of the two BiLSTM))
elmo = Elmo(options_file, weight_file, 2, dropout=0)

# use batch_to_ids to convert sentences to character ids
sentences = [['1tb', 'of', 'mechanical', 'storage', 'is', "n't", 'bad', '"', 'but', 'toshiba', 'hard', 'drives', 'really', 'are', "n't", 'what', 'we', 'want', 'to', 'be', 'seeing', 'as', 'they', 'tend', 'to', 'be', 'a', 'bit', 'slower', 'than', 'competing', 'drives', 'from', 'hgst', '"', 'western', 'digital', '"', 'samsung', '"', 'and', 'seagate', '.'], ['amazon', 'is', 'another', 'good', 'choice', '"', 'and', 'i', 'actually', 'prefer', 'their', 'interface', 'better', 'than', 'itunes', '', '(', 'it', 'loads', 'faster', 'for', 'me', ')', '.'], ['well-designed', '"', 'properly', 'constructed', 'timber', 'buildings', 'can', 'be', 'even', 'safer', 'in', 'earthquakes', 'than', 'ferro-concrete', 'ones', '.'], ['maybe', 'it', 's', 'because', 'i', 'm', 'a', 'ku', 'fan', '"', 'but', 'i', 'honestly', 'like', 'the', 'looks', 'of', 'adidas', 'uniforms', 'better', 'than', 'nike', '.'], ['soft', 'drinks', 'do', 'not', 'include', 'beverages', 'that', 'contain', 'milk', 'or', 'milk', 'products', '"', 'soy', '"', 'rice', 'or', 'similar', 'milk', 'substitutes', '"', 'or', 'greater', 'than', '50', '%', 'of', 'vegetable', 'or', 'fruit', 'juice', 'by', 'volume', '.'], ['partly', 'because', 'i', 'like', 'apple', 's', 'choice', 'of', 'file', 'format', '-', 'aac', 'is', 'much', 'more', 'modern', 'than', 'mp3', '"', 'and', 'theoretically', 'an', 'aac', 'file', 'at', '256kbps', '(', 'from', 'itunes', 'plus', ')', 'sounds', 'better', 'than', 'an', 'mp3', 'file', 'at', '256kbps', '(', 'from', 'amazon', ')', '.'], ['and', 'nokia', 'is', 'easier', 'to', 'use', '...', '...', 'it', 'easily', 'gets', 'infected', 'with', 'virus', 'and', 'the', 'net', 'speed', 'is', 'not', 'fast', '...', '..and', 'ofcourse', 'nokia', 'is', 'way', 'more', 'reliable', 'than', 'samsung', '...', '..go', 'for', 'nokia', '...', '..this', 'phone', 'suxxxxxxxxxxxxxxxxxxxxxx', '!'], ['java', 'is', 'a', 'static', 'type', 'language', 'and', 'it', 'is', 'safer', 'than', 'dynamic', 'type', 'languages', 'like', 'ruby', '.'], ['amazon', 'music', 'will', 'be', 'cheaper', '"', 'faster', 'and', 'perceived', 'to', 'be', 'more', 'honest', 'than', 'itunes', 'both', 'by', 'customers', 'and', 'musicians', '.'], 
             ['we', 'have', 'found', 'that', 'blood', 'carbon', 'and', 'nitrogen', 'turnover', 'was', 'roughly', 'equivalent', 'in', 'mice', 'and', 'in', 'rats', '"', 'and', 'that', 'mouse', 'blood', 'turned', 'over', 'slightly', 'faster', 'than', 'rat', 'blood', '.']]

character_ids = batch_to_ids(sentences)

embeddings = elmo(character_ids)


In [41]:
elmo.get_output_dim()

1024

In [16]:
character_ids.size()

torch.Size([10, 44, 50])

In [12]:
character_ids[2][2]

tensor([259, 113, 115, 112, 113, 102, 115, 109, 122, 260, 261, 261, 261, 261,
        261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
        261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
        261, 261, 261, 261, 261, 261, 261, 261])

In [38]:
print (embeddings['elmo_representations'][1][5][5])

tensor([-0.4785, -0.4598, -0.0396,  ..., -0.1577, -0.3011, -0.1590],
       grad_fn=<SelectBackward>)


In [39]:
print (embeddings['elmo_representations'][0][5][5])

tensor([-0.4785, -0.4598, -0.0396,  ..., -0.1577, -0.3011, -0.1590],
       grad_fn=<SelectBackward>)


## birnn 

In [ ]:
BiRNNCNN

In [1]:
! python3 main.py --train "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv" --dev "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test.csv" --test "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv" --data-io connl-ner-2003 --evaluator f1-alpha-match-10 --model BiRNNCRF --opt adam --lr 0.001 --save-best yes --patience 20 --rnn-hidden-dim 200 --gpu 1 --test "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test.csv" --save "BiRNNCFR.hdf5" 

args train = /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv: 2619 samples, 74616 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test.csv: 523 samples, 14728 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test.csv: 523 samples, 14728 words.
word_sequences_dev 523 [['and', 'can', 'i', 'just', 'say', 'that', 'doing', 'the', 'inferno', 'move', 'on', 'the', 'ds', 'is', '50', 'times', 'easier', 'than', 'trying', 'to', 'make', 'an', 'infinity', 'symbol', 'using', 'the', 'wii', 'remote', '.'], ['i', 'go', 'to', 'the', 'amazon', 'mp3', 'store', '(', 'better', 'than', 'itunes', '.'], ['tea', 'dinner', '(', 'sorry', '"', 'my', 'wife', 'is', 'trying', 'to', 'make', 'me', 'posherer', ')', 'and', 'picking', 'up', 'a', 'phone', 'is', 'easier', '-', 'then', 'i', 'can', 'swig', 'my', 'beer', 'and', 'relaaaaxxxx', '...', '.', '.'], ['actually', '

In [1]:
import torch
torch.cuda.is_available()

True

In [ ]:
! python3 main.py --train "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv" --dev "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv" --data-io connl-ner-2003 --evaluator f1-alpha-match-10 --opt adam --lr 0.001 --save-best yes --patience 20 --rnn-hidden-dim 200 --gpu 1 --test "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test.csv" --epoch-num 50 --isElmo True --save "regular_elmo.hdf5"

args train = /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv: 2619 samples, 74616 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv: 350 samples, 10092 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test.csv: 523 samples, 14728 words.
DatasetsBank: len(unique_words_list) = 7143 unique words.
DatasetsBank: len(unique_words_list) = 7600 unique words.
DatasetsBank: len(unique_words_list) = 8167 unique words.

load_vocabulary_from_tag_sequences:
 -- class_num = 7
 -- {'<pad>': 0, 'O': 1, 'B-OTHOBJ': 2, 'B-ASPOBJ': 3, 'B-ASP': 4, 'I-ASP': 5, 'I-ASPOBJ': 6, 'I-OTHOBJ': 7}
in main
True
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_weights.hdf5
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_options.json
init targer base
True
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_5

In [1]:
! python3 main.py --train "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv" --dev "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv" --data-io connl-ner-2003 --evaluator f1-alpha-match-10 --opt adam --lr 0.001 --save-best yes --patience 20 --rnn-hidden-dim 200 --gpu 1 --test "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_qw_new.csv" --epoch-num 50 --isElmo True --save "new_tagger1.hdf5"

args train = /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv: 2619 samples, 74616 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv: 350 samples, 10092 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_qw_new.csv: 63 samples, 322 words.
DatasetsBank: len(unique_words_list) = 7143 unique words.
DatasetsBank: len(unique_words_list) = 7600 unique words.
DatasetsBank: len(unique_words_list) = 7604 unique words.

load_vocabulary_from_tag_sequences:
 -- class_num = 7
 -- {'<pad>': 0, 'O': 1, 'B-OTHOBJ': 2, 'B-ASPOBJ': 3, 'B-ASP': 4, 'I-ASP': 5, 'I-ASPOBJ': 6, 'I-OTHOBJ': 7}
in main
True
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_weights.hdf5
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_options.json
init targer base
True
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_51

In [2]:
from allennlp.modules.elmo import Elmo, batch_to_ids

In [ ]:
import sys
sys.path.append('/home/vika/NER_RNN/targer')
from src.factories.factory_tagger import TaggerFactory

model = TaggerFactory.load(PATH_TO_PRETRAINED + MODEL_NAME)
model.cuda(device=1)
model.gpu = 1
tags = model.predict_tags_from_words(words)

In [1]:
! python3 main.py --train "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train_new.csv" --dev "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv" --data-io connl-ner-2003 --evaluator f1-alpha-match-10 --opt adam --lr 0.001 --save-best yes --patience 20 --rnn-hidden-dim 200 --gpu 1 --test "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test_new.csv" --epoch-num 50 --isElmo True --save "new_tagger1.hdf5"

args train = /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train_new.csv
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train_new.csv: 2719 samples, 75117 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv: 350 samples, 10092 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test_new.csv: 584 samples, 15032 words.
DatasetsBank: len(unique_words_list) = 7144 unique words.
DatasetsBank: len(unique_words_list) = 7601 unique words.
DatasetsBank: len(unique_words_list) = 8171 unique words.

load_vocabulary_from_tag_sequences:
 -- class_num = 8
 -- {'<pad>': 0, 'tag': 1, 'O': 2, 'B-OTHOBJ': 3, 'B-ASPOBJ': 4, 'B-ASP': 5, 'I-ASP': 6, 'I-ASPOBJ': 7, 'I-OTHOBJ': 8}
in main
True
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_weights.hdf5
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_options.json
init targer base
True
/home/vika/NER_RNN/targer/em

In [5]:
!pwd

/home/vika/NER_RNN/targer
