In [2]:
! python3 main.py --train "/home/vika/targer/data/NER/Indian_dataset/train.csv" --dev "/home/vika/targer/data/NER/Indian_dataset/dev.csv" --data-io connl-ner-2003 --evaluator f1-alpha-match-10 --model 'BiRNN' --opt adam --lr 0.001 --save-best yes --patience 20 --rnn-hidden-dim 200 --gpu 1 --batch-size 16 --test "/home/vika/targer/data/NER/Indian_dataset/test.csv" --bert True

Using TensorFlow backend.
args train = /home/vika/targer/data/NER/Indian_dataset/train.csv
Loading from /home/vika/targer/data/NER/Indian_dataset/train.csv: 23999 samples, 448609 words.
Loading from /home/vika/targer/data/NER/Indian_dataset/dev.csv: 1803 samples, 33827 words.
Loading from /home/vika/targer/data/NER/Indian_dataset/test.csv: 1093 samples, 18921 words.
DatasetsBank: len(unique_words_list) = 16615 unique words.
DatasetsBank: len(unique_words_list) = 17208 unique words.
DatasetsBank: len(unique_words_list) = 17829 unique words.
qu False
4
create seq indexer BERT!
Bert model loaded succesifully

load_vocabulary_from_tag_sequences:
 -- class_num = 5
 -- {'<pad>': 0, 'NONE': 1, 'PROD1': 2, 'PRED': 3, 'ASP': 4, 'PROD2': 5}
word_sequences_train 23999
[['however', 'it', 'be', 'better', 'in', 'so', 'many', 'ways', 'such', 'as', 'image', 'quality', 'and', 'handle', 'that', 'i', 'have', 'to', 'say', 'i', 'think', 'it', 'be', 'only', 'marginally', 'overpriced'], ['i', 'upgraded', 'fr

In [4]:
!pwd

/home/vika/targer


In [33]:
from allennlp.modules.elmo import Elmo, batch_to_ids

options_file = "embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_options.json"
weight_file = "/home/vika/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_weights.hdf5"

# Compute two different representation for each token.
# Each representation is a linear weighted combination for the
# 3 layers in ELMo (i.e., charcnn, the outputs of the two BiLSTM))
elmo = Elmo(options_file, weight_file, 2, dropout=0)

# use batch_to_ids to convert sentences to character ids
sentences = [['1tb', 'of', 'mechanical', 'storage', 'is', "n't", 'bad', '"', 'but', 'toshiba', 'hard', 'drives', 'really', 'are', "n't", 'what', 'we', 'want', 'to', 'be', 'seeing', 'as', 'they', 'tend', 'to', 'be', 'a', 'bit', 'slower', 'than', 'competing', 'drives', 'from', 'hgst', '"', 'western', 'digital', '"', 'samsung', '"', 'and', 'seagate', '.'], ['amazon', 'is', 'another', 'good', 'choice', '"', 'and', 'i', 'actually', 'prefer', 'their', 'interface', 'better', 'than', 'itunes', '', '(', 'it', 'loads', 'faster', 'for', 'me', ')', '.'], ['well-designed', '"', 'properly', 'constructed', 'timber', 'buildings', 'can', 'be', 'even', 'safer', 'in', 'earthquakes', 'than', 'ferro-concrete', 'ones', '.'], ['maybe', 'it', 's', 'because', 'i', 'm', 'a', 'ku', 'fan', '"', 'but', 'i', 'honestly', 'like', 'the', 'looks', 'of', 'adidas', 'uniforms', 'better', 'than', 'nike', '.'], ['soft', 'drinks', 'do', 'not', 'include', 'beverages', 'that', 'contain', 'milk', 'or', 'milk', 'products', '"', 'soy', '"', 'rice', 'or', 'similar', 'milk', 'substitutes', '"', 'or', 'greater', 'than', '50', '%', 'of', 'vegetable', 'or', 'fruit', 'juice', 'by', 'volume', '.'], ['partly', 'because', 'i', 'like', 'apple', 's', 'choice', 'of', 'file', 'format', '-', 'aac', 'is', 'much', 'more', 'modern', 'than', 'mp3', '"', 'and', 'theoretically', 'an', 'aac', 'file', 'at', '256kbps', '(', 'from', 'itunes', 'plus', ')', 'sounds', 'better', 'than', 'an', 'mp3', 'file', 'at', '256kbps', '(', 'from', 'amazon', ')', '.'], ['and', 'nokia', 'is', 'easier', 'to', 'use', '...', '...', 'it', 'easily', 'gets', 'infected', 'with', 'virus', 'and', 'the', 'net', 'speed', 'is', 'not', 'fast', '...', '..and', 'ofcourse', 'nokia', 'is', 'way', 'more', 'reliable', 'than', 'samsung', '...', '..go', 'for', 'nokia', '...', '..this', 'phone', 'suxxxxxxxxxxxxxxxxxxxxxx', '!'], ['java', 'is', 'a', 'static', 'type', 'language', 'and', 'it', 'is', 'safer', 'than', 'dynamic', 'type', 'languages', 'like', 'ruby', '.'], ['amazon', 'music', 'will', 'be', 'cheaper', '"', 'faster', 'and', 'perceived', 'to', 'be', 'more', 'honest', 'than', 'itunes', 'both', 'by', 'customers', 'and', 'musicians', '.'], ['we', 'have', 'found', 'that', 'blood', 'carbon', 'and', 'nitrogen', 'turnover', 'was', 'roughly', 'equivalent', 'in', 'mice', 'and', 'in', 'rats', '"', 'and', 'that', 'mouse', 'blood', 'turned', 'over', 'slightly', 'faster', 'than', 'rat', 'blood', '.']]

character_ids = batch_to_ids(sentences)

embeddings = elmo(character_ids)


In [41]:
elmo.get_output_dim()

1024

In [16]:
character_ids.size()

torch.Size([10, 44, 50])

In [12]:
character_ids[2][2]

tensor([259, 113, 115, 112, 113, 102, 115, 109, 122, 260, 261, 261, 261, 261,
        261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
        261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
        261, 261, 261, 261, 261, 261, 261, 261])

In [38]:
print (embeddings['elmo_representations'][1][5][5])

tensor([-0.4785, -0.4598, -0.0396,  ..., -0.1577, -0.3011, -0.1590],
       grad_fn=<SelectBackward>)


In [39]:
print (embeddings['elmo_representations'][0][5][5])

tensor([-0.4785, -0.4598, -0.0396,  ..., -0.1577, -0.3011, -0.1590],
       grad_fn=<SelectBackward>)


## birnn 

In [ ]:
BiRNNCNN

In [1]:
! python3 main.py --train "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv" --dev "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test.csv" --test "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv" --data-io connl-ner-2003 --evaluator f1-alpha-match-10 --model BiRNNCRF --opt adam --lr 0.001 --save-best yes --patience 20 --rnn-hidden-dim 200 --gpu 1 --test "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test.csv" --save "BiRNNCFR.hdf5" 

args train = /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv: 2619 samples, 74616 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test.csv: 523 samples, 14728 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test.csv: 523 samples, 14728 words.
word_sequences_dev 523 [['and', 'can', 'i', 'just', 'say', 'that', 'doing', 'the', 'inferno', 'move', 'on', 'the', 'ds', 'is', '50', 'times', 'easier', 'than', 'trying', 'to', 'make', 'an', 'infinity', 'symbol', 'using', 'the', 'wii', 'remote', '.'], ['i', 'go', 'to', 'the', 'amazon', 'mp3', 'store', '(', 'better', 'than', 'itunes', '.'], ['tea', 'dinner', '(', 'sorry', '"', 'my', 'wife', 'is', 'trying', 'to', 'make', 'me', 'posherer', ')', 'and', 'picking', 'up', 'a', 'phone', 'is', 'easier', '-', 'then', 'i', 'can', 'swig', 'my', 'beer', 'and', 'relaaaaxxxx', '...', '.', '.'], ['actually', '

In [1]:
import torch
torch.cuda.is_available()

True

In [ ]:
! python3 main.py --train "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv" --dev "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv" --data-io connl-ner-2003 --evaluator f1-alpha-match-10 --opt adam --lr 0.001 --save-best yes --patience 20 --rnn-hidden-dim 200 --gpu 1 --test "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test.csv" --epoch-num 50 --isElmo True --save "regular_elmo.hdf5"

args train = /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv: 2619 samples, 74616 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv: 350 samples, 10092 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test.csv: 523 samples, 14728 words.
DatasetsBank: len(unique_words_list) = 7143 unique words.
DatasetsBank: len(unique_words_list) = 7600 unique words.
DatasetsBank: len(unique_words_list) = 8167 unique words.

load_vocabulary_from_tag_sequences:
 -- class_num = 7
 -- {'<pad>': 0, 'O': 1, 'B-OTHOBJ': 2, 'B-ASPOBJ': 3, 'B-ASP': 4, 'I-ASP': 5, 'I-ASPOBJ': 6, 'I-OTHOBJ': 7}
in main
True
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_weights.hdf5
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_options.json
init targer base
True
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_5

In [1]:
! python3 main.py --train "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv" --dev "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv" --data-io connl-ner-2003 --evaluator f1-alpha-match-10 --opt adam --lr 0.001 --save-best yes --patience 20 --rnn-hidden-dim 200 --gpu 1 --test "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_qw_new.csv" --epoch-num 50 --isElmo True --save "new_tagger1.hdf5"

args train = /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train.csv: 2619 samples, 74616 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv: 350 samples, 10092 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_qw_new.csv: 63 samples, 322 words.
DatasetsBank: len(unique_words_list) = 7143 unique words.
DatasetsBank: len(unique_words_list) = 7600 unique words.
DatasetsBank: len(unique_words_list) = 7604 unique words.

load_vocabulary_from_tag_sequences:
 -- class_num = 7
 -- {'<pad>': 0, 'O': 1, 'B-OTHOBJ': 2, 'B-ASPOBJ': 3, 'B-ASP': 4, 'I-ASP': 5, 'I-ASPOBJ': 6, 'I-OTHOBJ': 7}
in main
True
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_weights.hdf5
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_options.json
init targer base
True
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_51

In [2]:
from allennlp.modules.elmo import Elmo, batch_to_ids

In [ ]:
import sys
sys.path.append('/home/vika/NER_RNN/targer')
from src.factories.factory_tagger import TaggerFactory

model = TaggerFactory.load(PATH_TO_PRETRAINED + MODEL_NAME)
model.cuda(device=1)
model.gpu = 1
tags = model.predict_tags_from_words(words)

In [1]:
! python3 main.py --train "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train_new.csv" --dev "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv" --data-io connl-ner-2003 --evaluator f1-alpha-match-10 --opt adam --lr 0.001 --save-best yes --patience 20 --rnn-hidden-dim 200 --gpu 1 --test "/home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test_new.csv" --epoch-num 50 --isElmo True --save "new_tagger1.hdf5"

args train = /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train_new.csv
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_train_new.csv: 2719 samples, 75117 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_dev.csv: 350 samples, 10092 words.
Loading from /home/vika/NER_RNN/targer/data/NER/Asqua_CAM_aspects/CAM_test_new.csv: 584 samples, 15032 words.
DatasetsBank: len(unique_words_list) = 7144 unique words.
DatasetsBank: len(unique_words_list) = 7601 unique words.
DatasetsBank: len(unique_words_list) = 8171 unique words.

load_vocabulary_from_tag_sequences:
 -- class_num = 8
 -- {'<pad>': 0, 'tag': 1, 'O': 2, 'B-OTHOBJ': 3, 'B-ASPOBJ': 4, 'B-ASP': 5, 'I-ASP': 6, 'I-ASPOBJ': 7, 'I-OTHOBJ': 8}
in main
True
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_weights.hdf5
/home/vika/NER_RNN/targer/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B_options.json
init targer base
True
/home/vika/NER_RNN/targer/em

In [5]:
!pwd

/home/vika/NER_RNN/targer
